### ISSUE TITLE
I am Getting Error

### ISSUE THREAD

**Issue by himanshu03vsk** [Abu3safeer/CR-dl-gui#1]
I entered my login details and pasted link of the video eg:"https://www.crunchyroll.com/radiant/episode-1-toward-a-new-adventure-overture-789393"
set the quality 1080p but it gives me error.
Any way to solve this?
![Capture](https://user-images.githubusercontent.com/58275123/69761740-48a4a780-118e-11ea-8a1d-2701f07a9e48.PNG)

**Comment by Abu3safeer** [comment]
Hello @himanshu03vsk ,

Sorry for taking too long to answer you.
The app now is V4, please try it and see what it can offer you.

**Comment by B00MST3R** [comment]
I'm constantly getting an error when trying it
![Error CR](https://user-images.githubusercontent.com/27199101/90348130-c93a6980-e077-11ea-9640-66e5c95c11c2.png)

**Comment by Abu3safeer** [comment]
The error message is very clear, the system cannot find the exe file of cr-dl.
you need to make sure both cr-dl-gui and cr-dl in the same folder

**Comment by B00MST3R** [comment]
Ah Ignore my first post, wasn't sure if I was Necro Posting so I thought it'd be better to start a new thread, my apologies, and thank you for helping me there

**Comment by B00MST3R** [comment]
Also Many Many Thanks
